### ISSUE TITLE
Multiple AD Domains?

### ISSUE THREAD

**Issue by bwosborne2** [overtrue/laravel-saml#1]
Does this support multiple AD / SAML domains?

**Comment by overtrue** [comment]
Did you mean multi Idp? https://github.com/overtrue/laravel-saml#idp-configuration-resolver

**Comment by bwosborne2** [comment]
Multi IdP is a SAMl solution. ldaprecord uses ldap. I have been using a predecessor f this (adldap) for years with succes son a single domain. In fact, ldaprecord is what drew me to use aravel.

My current plans are to use ldaprecord in the short term while working with our identity trams to move toward Socialstream & Socialite Providers.
I expect to use the OAuth based Microsoft Azure provider for one domain & the SAML based Microsoft provider for the other one.

In my personal opinion I feel I cannot depend on this developer to provide necessary support for their code so I will work on moving my projects to something else.
