### ISSUE TITLE
Usage of Saml::configureIdpUsing()

### ISSUE THREAD

**Issue by Vicftz** [overtrue/laravel-saml#2]
Hi overtrue !

Hope you're well. I implement your SAML package and I got some trouble with multiple idp.
Do you have any example of usage of this function (Saml::configureIdpUsing()) ?
Where should I put it exactly in my code?

Thank you,

**Comment by overtrue** [comment]
@Vicftz For example, your application has many idps from user-configured, you store these configs in the database, you can configure Idp when calling such as following:

```php
Saml::configureIdpUsing(function($idpName): array {
    $idp = Idp::where('name', $idpName)->first();  // fetch from database
    return [
        // https://github.com/overtrue/laravel-saml/blob/master/config/saml.php#L81-L137
        'entityId' => $idp->entityId,
        'x509cert' => $idp->x509cert,
        //...
    ];
});
```

**Comment by Vicftz** [comment]
Hi @overtrue,

Thank you for your response. I did exactly what you said, but I still got this error : 

`SAML Assertion failed: The response was received at https://180e-195-154-25-21.eu.ngrok.io/saml/acs instead of https://2862-195-154-25-21.eu.ngrok.io/saml/acs?idp=google`

I try to understand how your code work and the problem come from this method in the method "isValid($requestId = null)" from Response.php, who remove the ?idp=google for the currentUrl.

<img width="382" alt="Capture d’écran 2022-04-25 à 10 40 20" src="https://user-images.githubusercontent.com/36641184/165052823-126a8059-67e7-461f-91d4-73b0774560e1.png">

Do you have any idea ?

**Comment by overtrue** [comment]
@Vicftz  I also encountered this problem, my solution is store the idp information to session and fetch id on callback controller.

**Comment by overtrue** [comment]
FYI.

```php
    public function login(Idp $idp): \Illuminate\Http\RedirectResponse
    {
        $redirect = Saml::idp($idp->slug)->redirect();
        
        \session(['saml.idp' => $idp]);
        
        return $redirect;
    }
   
    public function acs(Request $request): \Illuminate\Http\RedirectResponse
    {
        $idp = \session('saml.idp');
        
        \abort_if(!$idp, 400, 'Invalid request!');

        $samlUser = Saml::idp($idp->slug)->getAuthenticatedUser();
        
        $samlUserId = $samlUser->getNameId();
        
        // create user 
        // $user = User::create(...)

        \Auth::set($user);
        
        return redirect('/');
    }
```

**Comment by overtrue** [comment]
@Vicftz Hello, Where did you take the screenshot of this line of code?

![image](https://user-images.githubusercontent.com/1472352/165061186-49b1afb4-462a-49ab-b9bb-8c6f30090375.png)
