### ISSUE TITLE
Metadata with multiple IDPs

### ISSUE THREAD

**Issue by razvan-deskare** [overtrue/laravel-saml#3]
Hi, 

I got a little trouble in my SAML SSO development.
Is it possible to generate metadata without any default IDP ? I implemented multiple IdP (Each client will have his own idp, stored in my database).
As the he metadata are not linked to the IDP, I want to give the same link to all my customers (ex : laravel.test/saml/metadata).
But I need an IDP to build this object : 
`$auth` = Saml::idp();`
(I commented the idp part in my config).
Do you have an idea ?

Thank you.

**Comment by overtrue** [comment]
@razvan-deskare Hi,  you can follow this issue: https://github.com/overtrue/laravel-saml/issues/2

```php
Saml::configureIdpUsing(function($idpName): array {
    $idp = Idp::where('name', $idpName)->first();  // fetch from database
    return [
        // https://github.com/overtrue/laravel-saml/blob/master/config/saml.php#L81-L137
        'entityId' => $idp->entityId,
        'x509cert' => $idp->x509cert,
        //...
    ];
});
```

then you can create auth instance for specify IDP:

```php
$auth = Saml::idp($idpName); 
```

**Comment by razvan-deskare** [comment]
Thank you for your quick answer.

But I as mentioned before, I would like to generate my metadate based on no IdP. Is it possible, or do I still need to create a "dummy" IdP in order to generate them?

Thank you.

**Comment by overtrue** [comment]
@razvan-deskare Hi, I've fixed it:

```php
    //<...>
    public function metadata(Request $request)
    {
        if ($request->has('download')) {
            return Saml::getMetadataXMLAsStreamResponse();
            // or specify a filename to the xml file:
            // return Saml::getMetadataXMLAsStreamResponse('sp-metadata.xml');
        }
        
        return Saml::getMetadataXML();
    }
```
