### ISSUE TITLE
Avoid using `url()` in saml.php, even if it is `env()`

### ISSUE THREAD

**Issue by alucard001** [overtrue/laravel-saml#4]
To reproduce:

- Install Laravel 9 by running: `composer create-project laravel/laravel .`
- Publish config by running: `php artisan vendor:publish --tag=saml-config`
- Start server by running `php artisan serve`, error below:

```
In UrlGenerator.php line 121:

  Illuminate\Routing\UrlGenerator::__construct(): Argument #2 ($request) must be of type Illuminate\Http\Request, null given, called in C:\projects\sso\vendor\laravel\framework\s   
  rc\Illuminate\Routing\RoutingServiceProvider.php on line 65
```

After reading this: https://stackoverflow.com/questions/72520085/illuminate-routing-urlgenerator-construct-argument-2-request-must-be-o, the root cause is that in your `saml.php` there are several config that is using this helper function: `url()`.

It will still fail even if you are coding this: `env('MY_ENV_VAR', url('/'))` when this variable is set in `.env`.  `url()` will still run in config file `saml.php`.

After removing all `url()`, I can start my server.

Please take a look and modify your `saml.php` config accordingly.

Thank you.

**Comment by overtrue** [comment]
Thanks.
